### ISSUE TITLE
关于视图

### ISSUE THREAD

**Issue by niki668** [Julienedies/crx-bookmarks2#1]
亲爱的,你的书签管理拓展做的非常棒,正在使用中!
想提个建议,目前书签的卡片视图没有截图显示,另外视图也不支持自定义宽度,如果有可能,希望能越来越完美.感谢你为Chrome做的标签增强.

**Comment by Julienedies** [comment]
@niki668 ，谢谢反馈和建议。  
因为主要是满足自己的使用需求，这个扩展有很多地方都没完善。 
现在实在没有精力和时间，后续会找时间好好优化升级一下。 
欢迎继续提出建议。

**Comment by Julienedies** [comment]
@niki668  截图显示的功能貌似无法简单实现，另外感觉意义不大，还是文字更清楚明白。
自定义宽度 这个可以在五一的时候做一下。
